# Tanks and Temples dataset
dataset: llff #! change from nsvf 
image_batching: false
factor: 0
num_coarse_samples: 64
num_fine_samples: 128
use_viewdirs: false
white_bkgd: false  # No alpha channel #! change from true to false
batch_size: 1024
randomized: true
sh_deg: 4
max_steps: 100000 #! changed from 200 to 1000 to 100000
near: 0.0
far: 4.0
sparsity_radius: 5.0
sparsity_length: 0.2
#! max_steps: 2000000